var PHP_ZTS ="yes"
var PHP_DEBUG="no"
var PHP_DLL_LIB ="php7ts.lib"
var PHP_DLL ="php7ts.dll"
var PHP_SECURITY_FLAGS ="no"
var PHP_ANALYZER ="no"
var PHP_PGO ="no"
var PHP_PGI ="no"
var PHP_ALL_SHARED ="no"

